name: DNA_Methylation
channels:
  - defaults
dependencies:
  - pandas=1.1.2
  - scikit-learn=0.23.2
  - matplotlib
  - plotly
  - pip
  - python=3.7
  - pip:
    - google-api-core==1.23.0
    - google-auth==1.23.0
    - google-cloud-core==1.4.3
    - google-cloud-storage==1.32.0
    - google-crc32c==1.0.0
    - google-resumable-media==1.1.0
    - googleapis-common-protos==1.52.0
    - idna==2.10
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - requests==2.24.0
    - rsa==4.6
    - urllib3==1.25.11
    - xgboost==1.2.1
