trainingInput:
  hyperparameters:
    goal: MAXIMIZE
    maxTrials: 15
    maxParallelTrials: 0
    hyperparameterMetricTag: f1_score_micro
    enableTrialEarlyStopping: TRUE
    params:
    - parameterName: ccp_alpha
      type: DOUBLE
      minValue: 0.000001
      maxValue: 0.5
      scaleType: UNIT_LOG_SCALE
    - parameterName: max_features
      type: INTEGER
      minValue: 10
      maxValue: 150
      scaleType: UNIT_LINEAR_SCALE
    - parameterName: max_depth
      type: INTEGER
      minValue: 5
      maxValue: 50
      scaleType: UNIT_LINEAR_SCALE